import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className="min-h-screen bg-[#FFE5D4] text-[#7F8C8D] font-sans">
                <div className="min-h-screen bg-gradient-to-b from-[#B3DFF2] via-[#F6E8D6] to-[#FFE5D4]">{children}</div>
            </body>
        </html>
    );
}
